version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=rancherserver.westcentralus.cloudapp.azure.com/
