version: "2"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
 #   volumes:
 #     - "/var/run/docker.sock:/var/run/docker.sock"
 #     - nginx-data-external:/etc/nginx
    command: "git clone https://bf101f78fc7bbe817c2027db8db443640ef19cbb:x-oauth-basic@github.com/steveneighbour/docker-nginx-letsencrypt-sample.git"
    labels:
       io.rancher.container.pull_image: always
    links:
     - nginx:nginx

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
 #   volumes:
 #     - "/var/run/docker.sock:/tmp/docker.sock"
 #     - nginx-data-external:/etc/docker-gen
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    labels:
       io.rancher.container.pull_image: always
    links:
     - nginx:nginx
    
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
 #   volumes:
 #     - "/var/run/docker.sock:/var/run/docker.sock"
 #     - nginx-data-external:/etc/nginx
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    labels:
       io.rancher.container.pull_image: always
    links:
     - nginx:nginx
    
#  sample-api:
#    restart: always
#    image: sample-api
    #build: ./samples/api
#    container_name: sample-api
#    environment:
#     - VIRTUAL_HOST=rancherserver.westcentralus.cloudapp.azure.com
#      - VIRTUAL_NETWORK=nginx-proxy
#      - VIRTUAL_PORT=3000
#      - LETSENCRYPT_HOST=rancherserver.westcentralus.cloudapp.azure.com
#      - LETSENCRYPT_EMAIL=steve.neighbour@gmail.com

#  sample-website:
#    restart: always
#    image: sample-website
    #build: ./samples/website
#    container_name: sample-website
#    volumes:
#      - "./volumes/nginx-sample-website/conf.d/:/etc/nginx/conf.d"
#      - "./volumes/config/sample-website/config.js:/usr/share/nginx/html/config.js"
#    environment:
#      - VIRTUAL_HOST=samplewebsite.example.com
#      - VIRTUAL_NETWORK=nginx-proxy
#      - VIRTUAL_PORT=80
#      - LETSENCRYPT_HOST=rancherserver.westcentralus.cloudapp.azure.com
#      - LETSENCRYPT_EMAIL=steve.neighbour@gmail.com

volumes:
  nginx-data-external:
    #driver: local
    #external: true # Without this definition, a stack scoped volume will be created. 
    #command: git clone https://bf101f78fc7bbe817c2027db8db443640ef19cbb:x-oauth-basic@github.com/steveneighbour/docker-nginx-letsencrypt-sample.git
