version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d:/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: data-volume, nginx, whoami
    volumes_from:
      - data-volume
    command: 
      - cat && git clone https://bf101f78fc7bbe817c2027db8db443640ef19cbb:x-oauth-basic@github.com/steveneighbour/docker-nginx-letsencrypt-sample.git

  data-volume:
    tty: true
    image: alpine
    stdin_open: true

  nginx:
    image: nginx
    links:
      - whoami
    volumes:
      - "/etc/nginx/conf.d/"
    environment:
      VIRTUAL_HOST: rancherserver.westcentralus.cloudapp.azure.com
 #     LETSENCRYPT_HOST: rancherserver.westcentralus.cloudapp.azure.com
 #     LETSENCRYPT_EMAIL: steve.neighbour.com
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: data-volume, nginx, whoami
    volumes_from:
      - data-volume
      
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=rancherserver.westcentralus.cloudapp.azure.com
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: data-volume, nginx, whoami
    volumes_from:
      - data-volume
      

#  letsencrypt-nginx-proxy-companion:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    volumes:
#   #   - "/var/run/docker.sock:/var/run/docker.sock"
#    labels:
#      io.rancher.container.pull_image: always
#      io.rancher.sidekicks: data-volume, nginx, whoami, letsencrypt-nginx-proxy-companion
#    volumes_from:
#      - data-volume
